import re
from datetime import datetime
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, ContextTypes, filters

TOKEN_CALC = "8079185211:AAFTauMWDe-AUd4Q3N_4srsr4rq7wwI-qUc"

# =========================
# PARSE REPORT FUNCTION
# =========================
def parse_report(text: str):
    positives = 0.0
    negatives = 0.0
    clear_count = 0
    entries = 0

    title = "JDCLUB9VIP"

    for line in text.splitlines():
        if "Total" not in line:
            continue

        # Skip Clear
        if re.search(r"Total\s*:\s*Clear", line, re.IGNORECASE):
            clear_count += 1
            entries += 1
            continue

        # Capture number with comma / decimal / no decimal
        m = re.search(r"Total\s*:\s*([+\-]?\s*[\d,]+(?:\.\d+)?)", line)
        if not m:
            continue

        raw = m.group(1)
        raw = raw.replace(" ", "").replace(",", "")

        try:
            value = float(raw)
        except:
            continue

        entries += 1

        if value >= 0:
            positives += value
        else:
            negatives += value

    net = positives + negatives

    return title, entries, clear_count, positives, negatives, net


# =========================
# FORMAT MONEY
# =========================
def money(x: float) -> str:
    sign = "+" if x > 0 else ""
    return f"{sign}{x:,.2f}"


# =========================
# START COMMAND
# =========================
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "📌 JDCLUB9VIP FINANCE CALCULATOR BOT\n\n"
        "Cara guna:\n"
        "1️⃣ Paste report yang ada 'Total :'\n"
        "2️⃣ Bot akan auto kira Total In / Out / NET\n"
    )


# =========================
# MAIN CALCULATE HANDLER
# =========================
async def calc(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = update.message.text or ""

    title, entries, clear_count, pos, neg, net = parse_report(text)

    if entries == 0:
        await update.message.reply_text(
            "❌ Tiada data 'Total :' dijumpai.\n"
            "Sila paste report penuh."
        )
        return

    today = datetime.now().strftime("%d %b %Y")

    report = (
        f"📊 {title} NIGHT REPORT\n"
        f"🗓 Date : {today}\n\n"
        f"📋 Total Entries : {entries}\n"
        f"🧾 Clear Count   : {clear_count}\n\n"
        f"🟢 Total In   : {money(pos)}\n"
        f"🔴 Total Out  : {money(neg)}\n"
        f"💰 NET RESULT : {money(net)}\n\n"
        f"━━━━━━━━━━━━━━━━━━\n"
        f"Generated by JDCLUB9VIP Internal Finance Bot"
    )

    await update.message.reply_text(report)


# =========================
# RUN BOT
# =========================
app = ApplicationBuilder().token(TOKEN_CALC).build()

app.add_handler(CommandHandler("start", start))
app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, calc))

print("JDCLUB9VIP Calc Bot Running...")
app.run_polling()
